title: M. Haikel Oksama
logo: https://media.licdn.com/dms/image/v2/D5603AQHVPDSf0DUbDg/profile-displayphoto-shrink_800_800/B56ZUKkHkJHsAc-/0/1739638996302?e=1755129600&v=beta&t=5rEdg7Qqw7zgfXqr7BkN1Hl-u9d9T6OrxzJlK9-MDFo
description: Full-Stack Developer | Laravel | Kotlin | Go Enthusiast
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
